### PR TITLE
Blowfish encryptor

### PR DESCRIPTION
**Pull request by mxsb**
Added a Blowfish based implementation of the Encryptor interface.

### CODE REVIEW

**Comment by mxsb** [comment]
Thx for merging. Are there any plans for a new release in the near future?

**Comment by rajneeshpatel** [comment]
Should get some time this week. Nag me if you don't see progress

On Sun, 6 Mar 2016 8:34 am Max Schwaab, <notifications@github.com> wrote:

> Thx for merging. Are there any plans for a new release in the near future?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsendnsca/jsendnsca/pull/14#issuecomment-192829949>.
>
-- 
Raj Patel - 07957 446908

**Comment by rajneeshpatel** [comment]
Hi Max,

Managed to cut a release.

https://github.com/jsendnsca/jsendnsca/releases/tag/v2.1.0

Hopefully this is OK, let me know if any issues.

Thanks

On Sun, 6 Mar 2016 at 23:19 Raj Patel <rajneeshpatel@gmail.com> wrote:

> Should get some time this week. Nag me if you don't see progress
>
> On Sun, 6 Mar 2016 8:34 am Max Schwaab, <notifications@github.com> wrote:
>
>> Thx for merging. Are there any plans for a new release in the near future?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jsendnsca/jsendnsca/pull/14#issuecomment-192829949>.
>>
> --
> Raj Patel - 07957 446908
>
-- 
Raj Patel - 07957 446908

**Comment by mxsb** [comment]
Hey Raj,

thanks the quick action.
Is this available at Maven Central too?

I'm thinking about a Spring Boot starter and an auto configuration for
jsendnsca.

Maybe I'll prepare something at the weekend based on the current release..

Best

Max

**Comment by rajneeshpatel** [comment]
Hi Max,

Regarding Maven Central, something on my to do list for many years. Saying that, I have more time at the moment and intend to make some progress on this. Do you have any experience on this front?

I have more experience of Dropwizard myself but Spring Boot starter sounds interesting.

Thanks

Raj

**Comment by mxsb** [comment]
Regarding Maven Central, no experience up to now. But I can make up my mind on this topic.
Regarding Spring Boot, there is some experience and I'm enjoying to learn more.
We can connect on G+, Twitter or via email to continue the chat if you like...

**Comment by mxsb** [comment]
Regarding Maven Central, no experience up to now. But I can make up my mind on this topic.
Regarding Spring Boot, there is some experience and I'm enjoying to learn more.
We can connect on G+, Twitter or via email to continue the chat if you like...

**Comment by mxsb** [comment]
got Spring Boot starter and auto configuration running. will add some logging to the project the next days an do another pr..
I saw dropwizard is already using jsendnsca :)

**Pull request merged**
